### ISSUE TITLE
AMO disassembly differs from Spike

### ISSUE THREAD

**Issue by scottj97** [rems-project/sail-riscv#26]
The way Sail displays the operands in an AMO is inconsistent with Spike's disassembler. Here's one from Sail:
```
[882] [M]: 0x0000000080000620 (0xA514252F) amomax.w.aq a0, fp, a7
```

The same opcode from Spike displays as:
```
amomax.w a0, a7, (fp)
```

The 2nd and 3rd operands are reversed. It's especially confusing because the operand referring to the memory address is not shown in parentheses as other instructions do.

**Comment by pmundkur** [comment]
thanks for catching this.
