### ISSUE TITLE
CSRR* instruction disassembly has operands out of order

### ISSUE THREAD

**Issue by scottj97** [rems-project/sail-riscv#34]
The RISC-V Unprivileged Spec table 25.3 (pseudoinstructions) shows CSRRW (etc) instruction operands in the following order: `rd, csr, rs`. The Sail disassembly seems to have them as: `rd, rs, csr`.

**Comment by rmn30** [comment]
Thanks. This is an easy fix but I will leave it until #35 is done because otherwise we'll get conflicts
