### ISSUE TITLE
CSR instruction disassembly has numbers instead of mnemonics

### ISSUE THREAD

**Issue by scottj97** [rems-project/sail-riscv#35]
This is a [known issue](https://github.com/rems-project/sail-riscv/commit/82c7152b7374d9c24b2464a055aa4cd140048717). Filing as an issue so I can subscribe and get notified when it gets fixed.

cc @rmn30

**Comment by rmn30** [comment]
Thanks for filing. I've done a bit of work on this but it is now blocked by https://github.com/rems-project/sail/pull/57
