### ISSUE TITLE
mstatus.SD (Some Dirty) not set when mstatus.FS=Dirty

### ISSUE THREAD

**Issue by scottj97** [rems-project/sail-riscv#39]
After #38 the mstatus.SD bit does not properly reflect the state of mstatus.FS. It should be 1 if either of XS/FS (and eventually the new VS field from the Vector extension) are Dirty.

**Comment by pmundkur** [comment]
right, i missed that.  do you have a small test that catches this case?

**Comment by scottj97** [comment]
Nothing I can share, sorry.

**Comment by pmundkur** [comment]
i pushed a fix

**Comment by scottj97** [comment]
Excellent, ca57c1be19447a5ec831292f0ca4081ffc13b436 looks good, thank you!
