### ISSUE TITLE
N-extension CSRs active despite MISA

### ISSUE THREAD

**Issue by scottj97** [rems-project/sail-riscv#50]
When `misa[13]==0` (Sail's default) the N-extension (user interrupts) is not present.

I observe that some of the N-extension behavior is properly dependent on `misa` (via `haveNExt()`) but not all.

# Expected behavior

Access to the N-extension CSRs (e.g. `ustatus`) should cause an illegal instruction exception.

Bits `mstatus[4]` (aka UPIE) and `mstatus[0]` (aka UIE) should be hardwired to 0.

# Actual behavior

No illegal instruction exception occurs.

UIE and UPIE are writable and retain the value last written.

**Comment by scottj97** [comment]
Note that in the older (ratified) privileged spec, the description of mstatus expressly states that UPIE and UIE are hardwired to 0 in the absence of the N extension.

In the latest privileged spec, those two bits are marked as "WPRI".

The Sail model can be compatible with both versions of the spec by hardwiring them to 0.

**Comment by pmundkur** [comment]
Great catch. I've pushed a fix to branch fix_next_csrs.  Do you have a test case for this?

**Comment by scottj97** [comment]
I don't have a good test case, but I confirm this fixes the issue I had observed.
