### ISSUE TITLE
Sv39 virtual address msb check missing?

### ISSUE THREAD

**Issue by scottj97** [rems-project/sail-riscv#58]
The priv spec (section 4.4.1 on "Addressing and Memory Protection") says:

> Instruction fetch addresses and load and store effective addresses, which are 64 bits, must have bits 63-39 all equal to bit 38, or else a page-fault exception will occur.

But I am seeing a case where the Sail model successfully performs a load, translating using bits [38:0] of the vaddr, and ignoring the upper bits. Spike (as expected) takes a load page fault.

**Comment by pmundkur** [comment]
Good catch; I'd noticed this ages ago but forgotten to fix it.  Branch `fix_invalid_vaddr` should fix this, but it would be great if you could verify.

**Comment by scottj97** [comment]
Tried it (Sv39 only) and it works great!

**Comment by pmundkur** [comment]
great, thanks.
