### ISSUE TITLE
CSRs that "should not exist" not handled well

### ISSUE THREAD

**Issue by tzwaenn** [rems-project/sail-riscv#65]
The written spec states for example "In systems with only M-mode, or with both M-mode and U-mode but without U-mode trap support, the medeleg and mideleg registers should not exist." which does not seem to be reflected in Sail. Same for sedeleg/sideleg without N extension. And similarly, a clause has been recently added that mcounteren should not exist in M mode only systems.
Finally, is_CSR_defined for the user mode counters seems to be off - it require p==User where I would expect haveUsrMode() as M or S mode can access the user mode counters (if user mode exists).

**Comment by pmundkur** [comment]
great catches, thanks!
