### ISSUE TITLE
htif_store on RV32 and terminal output not working.

### ISSUE THREAD

**Issue by ben-marshall** [rems-project/sail-riscv#69]
Hi there

I'm trying to run a "Hello World" program on the RV32 SAIL model, and can't get the terminal output to work properly.

I'm re-using the "HTIF" interface built into the `riscv_platform.sail` file, and can't understand how the `htif_store` function works on RV32.

https://github.com/rems-project/sail-riscv/blob/7dedd27a2f6fb48ad002eb21daa4ce0c54dc562c/model/riscv_platform.sail#L303

For RV64, it's easy, I store a single double-word to the `tohost` symbol/address and get working UART output when setting "device" to 0x1 and "cmd" to "0x1".

For RV32, I don't see how the `htif_store` function can work. It seems like the function processes the command immediately, every time 32-bits are written. This leads to duplicated output on the terminal (every char printed twice) and eventually a spurious command and a failure.

There's even a comment:

https://github.com/rems-project/sail-riscv/blob/7dedd27a2f6fb48ad002eb21daa4ce0c54dc562c/model/riscv_platform.sail#L315

suggesting this is necessary behaviour, but I can't understand why?

So, what is the recommended store/instruction sequence to get correct simulated terminal output when building the RV32 C-simulator?

Many thanks,
Ben

**Comment by pmundkur** [comment]
This wasn't really tested on RV32, where the write of the control fields are separated from the payload.  That comment assumed RV64.
